### ISSUE TITLE
How to transform the action function into low-level action signal?

### ISSUE THREAD

**Issue by RZFan525** [embodied-agent-interface/embodied-agent-interface#4]
Thank you for your amazing work! It's very insightful and helpful.

I don't know how you transform the action function into low-level action signals. Could you provide a detailed description if you don't mind? Also, when do you plan to release the paper?

Best,
Run-Ze

**Comment by JamesKrW** [comment]
Hi,

Thanks for the kind words! I'm glad you love this work.

We use "magic" actions, which only consider the final states of the objects. We don't use controller-level actions due to their high-failure rates in our experiments.

For VirtualHome, you can refer to their [evolving_graph](https://github.com/xavierpuigf/virtualhome/tree/master/virtualhome/simulation/evolving_graph). 

For Behavior, we implemented:
a) Evolving_graph similar to VirtualHome: [link](https://github.com/embodied-agent-interface/embodied-agent-interface/blob/main/src/behavior_eval/evolving_graph/evolving_graph.py).
b) A transition model for iGibson environment: [link](https://github.com/embodied-agent-interface/embodied-agent-interface/blob/main/src/behavior_eval/transition_model/action_env.py).

Our paper is arxived [here](https://arxiv.org/abs/2410.07166).

Best,
Kangrui

**Comment by percypeng5221** [comment]
Hi Kangrui,

Great work! Correct me if I'm wrong. So in this work, there are no actual simulation running, like a low-level controller outputing the control signals given proprioceptive information? I'm wondering how to turn on the rendering and see how the actual robot is moving and what's the success and failure motion. Cause in Appendix S.1 of the paper you said: 
> The first simulator is based on the iGibson framework [101], supporting visual rendering and physical simulations
via PyBullet.
Can this be done? 

Thanks!
Percy

**Comment by JamesKrW** [comment]
Hi Percy,

I just uploaded an [example](https://github.com/embodied-agent-interface/embodied-agent-interface/blob/main/examples/action_sequencing_simulation.ipynb) that demonstrates how to run rendering and simulation of our magic actions, which might help address your questions.

Kangrui

**Comment by JamesKrW** [comment]
Yes. Behavior team is working on it but unfortunately this is not supported for now.
